# Build Image
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /app

COPY ["cooking-service/cooking-service.csproj", "cooking-service/"]
COPY ["food-app-common/food-app-common.csproj", "food-app-common/"] 

RUN dotnet restore "cooking-service/cooking-service.csproj"
COPY . .
WORKDIR "/app/cooking-service"

RUN dotnet build "cooking-service.csproj" -c Release -o /app/build
FROM build as publish
RUN dotnet publish "cooking-service.csproj" -c Release -o /app/publish

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "cooking-service.dll"]

# Build Image
# docker build --rm -f Dockerfile -t cooking-service .
# docker run -it --rm -p 5056:80 cooking-service

# docker tag cooking-service arambazamba/cooking-service
# docker push arambazamba/cooking-service

# Injecting environment variables into the container
# docker run -it --rm -p 5056:80 cooking-service -e "App__2__AuthEnabled"="false"

# Browse using: 
# http://localhost:5056
