version: '3.4'

services: 
  catalog-service:
    image: catalog-service
    ports: 
      - "5051:80"
    environment:
      - App:UseSQLite=true
  orders-service:
    image: order-service
    ports:
      - "5052:80"
  food-shop:
    image: food-shop
    ports:
      - "5053:80"      
    environment:
      - ENV_CATALOG_API_URL=http://localhost:5051
      - ENV_ORDERS_API_URL=http://localhost:5052

    depends_on: 
      - catalog-service
      - orders-service