POST  http://localhost:7071/api/Counter/1 HTTP/1.1
content-type: application/json

{
    "operation": "add",
    "value": 1
}

###
POST  http://localhost:7071/api/Counter/1 HTTP/1.1
content-type: application/json

{
    "operation": "get"
}

###
POST  http://localhost:7071/api/Counter/1 HTTP/1.1
content-type: application/json

{
    "operation": "reset"
}

###
POST  http://localhost:7071/api/Counter/1 HTTP/1.1
content-type: application/json

{
    "operation": "get"
}