@ordersUrl = https://localhost:5002

### Add new order
POST {{ordersUrl}}/orders/create HTTP/1.1
content-type: application/json

{
    "id": "3",
    "type": "order",
    "customer": {
        "Id": "1",
        "name": "Anna Soproni",
        "email": "anna.soproni@integrations.hu",
        "address": {
            "street": "Am Himmel",
            "number": "1",
            "zip": "1190",
            "city": "Wien",
            "country": "Austria"
        }
    },
    "payment": {
        "type": "Bank Transfer",
        "account": "4567"
    },
    "items": [
        {
            "id": 3,
            "name": "Wiener Schnitzel",
            "price": 18,
            "quantity": 1
        }
    ],
    "total": 48,
    "shippingAddress" : {
        "street": "Am Himmel",
        "number": "1",
        "zip": "1190",
        "city": "Wien",
        "country": "Austria"
    }
}