FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /app

COPY ["notification-service/notification-service.csproj", "notification-service/"]
COPY ["food-app-common/food-app-common.csproj", "food-app-common/"] 

RUN dotnet restore "notification-service/notification-service.csproj"
COPY . .
WORKDIR "/app/notification-service"

RUN dotnet build "notification-service.csproj" -c Release -o /app/build
FROM build as publish
RUN dotnet publish "notification-service.csproj" -c Release -o /app/publish

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "notification-service.dll"]

# Build Image
# docker build --rm -f dockerfile -t notification-service .

# Run Image without env vars
# docker run -it --rm -p 5058:8080 notification-service

# Run Image with env vars
# docker run -it --rm -p 5058:80 notification-service -e "App:UserSQLite=true" -e "App:ConnectionStrings:SQLServerConnection=<SQLSERVER_CONNECTION_STRING>"

# Browse using: 
# http://localhost:5058
# http://localhost:5058/food
# http://localhost:5058/config

# Publish Image to dockerhub
# docker tag notification-service arambazamba/notification-service
# docker push arambazamba/notification-service