### Send a test mail
POST http://localhost:5008/send HTTP/1.1
Content-Type: application/json

{
    "subject": "A test mail",
    "text": "Explore - Let life surprise you!",
    "recipient": "alexander.kastil@integrations.at"
}

### Test simple pubsub
POST http://localhost:5008/pubsub-test HTTP/1.1
Content-Type: application/json

{
    "id": 1234,
    "subject": "A test mail" 
} 