# Build Image
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /build
COPY . .
RUN dotnet restore "graph-notification-service.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "graph-notification-service.dll"]

# Build Image
# docker build --rm -f dockerfile -t graph-notification-service .

# Run Image without env vars
# docker run -it --rm -p 5058:8080 graph-notification-service

# Run Image with env vars
# docker run -it --rm -p 5058:80 graph-notification-service -e "App:UserSQLite=true" -e "App:ConnectionStrings:SQLServerConnection=<SQLSERVER_CONNECTION_STRING>"

# Browse using: 
# http://localhost:5058
# http://localhost:5058/food
# http://localhost:5058/config

# Publish Image to dockerhub
# docker tag graph-notification-service arambazamba/graph-notification-service
# docker push arambazamba/graph-notification-service