# Build Image
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /app

COPY ["image-service/image-service.csproj", "image-service/"]
COPY ["food-app-common/food-app-common.csproj", "food-app-common/"] 

RUN dotnet restore "image-service/image-service.csproj"
COPY . .
WORKDIR "/app/image-service"

RUN dotnet build "image-service.csproj" -c Release -o /app/build
FROM build as publish
RUN dotnet publish "image-service.csproj" -c Release -o /app/publish

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "image-service.dll"]

# Build Image
# docker build --rm -f dockerfile -t image-service .

# Run Image without env vars
# docker run -it --rm -p 5051:80 image-service

# Run Image with env vars
# When using another value than "images" update the dockerfile line 13 and 14
# docker run -it --rm -p 5051:80 image-service -e "IMG_FOLDER_NAME=images" 

# Browse using: 
# http://localhost:5051/
# http://localhost:5051/settings

# Publish Image to dockerhub
# docker tag image-service arambazamba/image-service
# docker push arambazamba/image-service