apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-ui
  template:
    metadata:
      labels:
        app: config-ui                 
    spec:
      containers:
      - name: config-ui
        image: aznativedev.azurecr.io/config-ui:latest
        env: 
          - name: ENV_API_URL
            value: 'http://20.23.115.214'
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "0.4"
            memory: "128Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: config-ui-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: config-ui
---  