apiVersion: apps/v1
kind: Deployment
metadata:
  name: configapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-api
  template:
    metadata:
      labels:
        app: config-api                 
    spec:
      containers:
      - name: config-api
        image: aznativedev.azurecr.io/config-api:latest
        env: 
          - name: App__Environment
            value: production
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "0.4"
            memory: "256Mi"     
---
apiVersion: v1
kind: Service
metadata:
  name: config-api-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: config-api
---  